### ISSUE TITLE
Add timeout support to ElementProxy#visible? and friends

### ISSUE THREAD

**Issue by dvicory** [appfolio/ae_page_objects#111]
Currently if you call `visible?` on an element, there's a default 5 second timeout. In some cases this sort of timeout makes sense (for instance, you're waiting for an AJAX request to complete), but in many others it bloats Selenium test times.

We recently had a use case where a CSS hover menu effect was applied and so we knew that there was no reason to have to wait for 5 seconds to see if the hover happened. I think it'd be better to allow `visible?` to accept an optional `timeout` parameter. `visible?` and friends all make use of `wait_until_visible` which accepts this parameter. Without this parameter, the only workaround to a shorter timeout is reimplementing what `visible?` does for you, which seems pointless.

**Comment by dtognazzini** [comment]
Timeouts can be changed at any time via `Capybara.using_wait_time`:

```ruby
Capybara.using_wait_time(0) do
  assert_predicate menu, :visible?
end
```

In your use case, `visible?` should find the element and return (true) immediately. Only the failure case will wait the entire wait time. In the go-right case, the default timeout won't bloat the test suite.

For the AJAX use case, it's better to use `wait_until_visible` to communicate the expectation inherent in the test that the element won't be visible for some amount of time.

**Comment by dtognazzini** [comment]
This still seems worthwhile. Consider this case:

```ruby
some_page.some_element.visible?
```

If you want to specify the wait time for the visibility check, you might be tempted to use `Capybara.using_wait_time` like so:
```ruby
Capybara.using_wait_time(0) do
  some_page.some_element.visible?
end
```

However, this changes the wait time for `some_page.some_element` part as well, which you may not want to target. To change the wait time for only the visibility check you'd need to write:
```ruby
el = some_page.some_element
Capybara.using_wait_time(0) do
  el.visible?
end
```

This is a pretty annoying.

Capybara 2 adds a `wait:` parameter to all _polling_ methods. Seems worthwhile to add the same for the Aepos methods.
