### ISSUE TITLE
Why can't we use capybara 2.4.4?

### ISSUE THREAD

**Issue by mark-ellul** [appfolio/ae_page_objects#133]
Hi,

I was just wondering why capybara cannot be upgraded to the latest version?

What would be needed to be done to be able to get it upgraded?

Thanks and regards

Mark

**Comment by dtognazzini** [comment]
Hi @mark-ellul. This is a duplicate of #81

To answer your question: Capybara can be upgrade to the latest version, we just need somebody to do it. If you're so inclined, please submit a pull request. Thanks!
